version: '3.8'

services:
  proxy-pool-dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    # 赋予容器特权，以便在容器内手动运行 create_warp_pool.sh 等脚本进行调试
    privileged: true
    # 将项目目录挂载到容器的 /app 目录
    volumes:
      - .:/app
    # 让容器保持运行，以便可以通过 docker exec 进入
    command: tail -f /dev/null