version: '3.8'

services:
  proxy-pool-service:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true # 赋予容器特权，以便执行网络操作
    network_mode: "host" # 使用主机网络模式，让容器共享主机的网络堆栈
    volumes:
      - ./proxy_manager.log:/app/proxy_manager.log # 挂载日志文件 (可选)
    # 如果需要确保 WARP 配置文件持久化或从外部提供，可以考虑挂载 /var/lib/cloudflare-warp
    # volumes:
    #   - ./proxy_manager.log:/app/proxy_manager.log
    #   - warp-config:/var/lib/cloudflare-warp # 使用命名卷持久化 WARP 配置

# 可选：定义命名卷
# volumes:
#   warp-config: