version: '3.8'

services:
  warp-proxy-pool:
    image: ghcr.io/crisrain/warp-proxypool:latest
    container_name: warp-proxy-pool
    privileged: true
    network_mode: host
    environment:
      - API_SECRET_TOKEN=${API_SECRET_TOKEN}
      - POOL_SIZE=${POOL_SIZE:-3}
      - BASE_PORT=${BASE_PORT:-10800}
      - WARP_LICENSE_KEY=${WARP_LICENSE_KEY}
      - WARP_ENDPOINT=${WARP_ENDPOINT}
      - WARP_CONFIG_BASE_DIR=${WARP_CONFIG_BASE_DIR}
      - WARP_IPC_BASE_DIR=${WARP_IPC_BASE_DIR}
      - WARP_LOG_FILE=${WARP_LOG_FILE}
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ./iptables_rules:/etc/iptables
      - warp-configs:/var/lib/warp-configs
      - warp-sockets:/run/warp-sockets
      - warp-logs:/var/log
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    restart: always

volumes:
  warp-configs:
  warp-sockets:
  warp-logs: